# Numpy
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.
Numpy is one of the most important foundational packages for Numerical computing in python<br>
Some of the important things in Numpy<br>
1. ndrray - multidimensional array for fast array-oriented and broadcasting operations
2. Fast mathematical opertions without for loops
3. reading/writing array data to the disk
4. memory-mapped files
5. Linear Algebra, random number generation

### Usage for Data Analysis operations
1. Fast vectorized multidimentioanl array operation for data cleanup, subsetting, filtering and other operations
2. Sorting, unique and set operations
3. Descriptive statistics, aggregating and summarizing data
4. Merging and Joining heterogenous datasets
5. conditional logic as array expressions
6. group-wise data manipulations

Numpy gives tremendous performance difference

In [ ]:
a=range(0,20)
type(a)

In [ ]:
import numpy as np
an_arr = np.arange(100)# array
type(an_arr)

In [1]:
import numpy as np
an_arr = np.arange(100)# array

a_list = list(range(100))  #list



In [2]:
%time for _ in range(1000): an_arr2 = an_arr * 2

CPU times: total: 0 ns
Wall time: 0 ns


In [3]:
%time for _ in range(40): a_list2 = [x * 2 for x in a_list]

CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
list1=[2,3,5,6,7]
list1+list1

[2, 3, 5, 6, 7, 2, 3, 5, 6, 7]

In [5]:
list1=[2,3,5,6,7]
for i in list1:
    print(i*2)

4
6
10
12
14


In [ ]:
arr1=np.arange(10)
arr1*3

In [ ]:
arr1+arr1

Numpy is 10 to 100 times faster than pure python based counterparts

### Numpy ndarray - Multidimensional Array Object
`ndarray` is one of the most important feature of Numpy<br>
`ndarray` is multidimensional container of homogeneous data<br>
All the elements are of same type<br>
each `ndarray` has `shape` and data type given by `dtype` of the array

In [2]:
import numpy as np
data = np.random.randn(2, 3)
data


array([[-0.18645982,  0.21027156,  2.14781896],
       [ 1.58592936, -0.29002614,  0.02534333]])

In [ ]:
alist+alist

In [7]:
data+data

array([[ 0.76012191,  3.2498689 ,  2.15100651],
       [-1.97060549,  0.90175319,  2.25364978]])

above example each cell is added to each other

In [ ]:
data.shape

In [ ]:
type(alist)

In [ ]:
data.dtype

In [ ]:
var1='i am holding string data'


In [ ]:
var1
type(var1)

### Creating ndarrays
Easiest way to create array is to use `array` function. It accepts any sequence

In [8]:
data1 = [6, 7.5, 8, 5, 8]
array1 = np.array(data1)

In [9]:
array1

array([6. , 7.5, 8. , 5. , 8. ])

In [10]:
type(array1)

numpy.ndarray

In [11]:
data2 = (6, 7.5, 8, 5, 8)
arr2=np.array(data2)
arr2

array([6. , 7.5, 8. , 5. , 8. ])

In [12]:
type(arr2)

numpy.ndarray

In [ ]:
array1

We can also create multidimensional array using nested sequences

In [13]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
print(data2)
type(data2)
data2=np.array(data2)
print(data2)
data2.shape

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [14]:
array2 = np.array(data2)
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

`ndim` and `shape` attributes give dimension and shape respectively

In [15]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
data2=np.array(data2)
data2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
data2.ndim

2

In [ ]:
data2.shape

In [ ]:
data2.dtype

#### Other ways to create new arrays

`ones` - to create an array of 1s<br>
`zeros` - to create array of 0s<br>
`empty` - create array without initializing its values<br>
to create higher dimensional array pass the tuple as dimension of array<br>

#### Zero
`zero()` creates an array filled with zero values. arguement is an array or tulip with size of each dimension of the array

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((4, 4))

#### Ones
`ones()` - filled with one values.

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(4)

#### Empty
`empty()` function create an array of specified shape. Arguement is an array or tuple with lenght of each dimension of array<br>
Value created are random and empty array needs to be assigned before use<br>

In [4]:
arr1=np.empty((2, 3, 2))

arr1

array([[[1.10237176e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 2.79112158e+179]],

       [[3.27422266e+179, 2.72478263e-056],
        [4.66525847e-033, 3.34720025e-033],
        [1.51922115e-051, 3.37747440e-057]]])

In [5]:
arr2=np.empty(( 3, 2))

arr2

array([[0.18645982, 0.21027156],
       [2.14781896, 1.58592936],
       [0.29002614, 0.02534333]])

In [6]:
arr1.ndim

3

In [7]:
arr2.ndim

2

In [8]:
np.empty(2)

array([-5.37476069e-254,  1.36653698e+075])

In [9]:
arr=np.ones((2,3,2))
arr.dtype
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [10]:
arr1=np.zeros((5,3,3))
arr2.dtype

dtype('float64')

In [11]:
arr=np.ones((3,2,2))
arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

`np.empty` can give uninitialized garbage values with zeros

***
### Array Create Function
`array` - Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default<br>
`asarray` - Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list<br>
`ones`, `ones_like` - Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype<br>
`zeros`,`zeros_like` - Like ones and ones_like but producing arrays of 0s instead<br>
`empty`,`empty_like` - Create new arrays by allocating new memory, but do not populate with any values like ones and zeros<br>
`full`,`full_like` - Produce an array of the given shape and dtype with all values set to the indicated “fill value” full_like takes another array and produces a filled array of the same shape and dtype<br>
`eye`, `identity` Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

## Combining ndarray
New ndarrary can be created.<br>
`vstack()` and `hstack` are two popular methods<br>
`vstack()` - Vertical Stack<br>
`hstack()` - Horizontal Stack<br>
<br>

### Vertical Stack
Two or more array can be stacked vertically

In [1]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print('-----')
arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)
print('-----')


[[1 2 3]
 [4 5 6]]
-----
[[ 7  8  9]
 [10 11 12]]
-----


In [2]:
arr3 = np.vstack((arr1, arr2))
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### Horizontal Stack
Two or more ndarray can be stacked horizontally

In [3]:
#import numpy as np
arr3 = np.hstack((arr1, arr2))
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


### Concatenating ndarray
`concatenate()` take a sequence (tuple, list etc) and join them along input axis

In [4]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr2)

[[ 7  8  9]
 [10 11 12]]


In [6]:
arr3 = np.concatenate([arr1, arr2])
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [7]:
arr3 = np.concatenate([arr1, arr2],axis=0)
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [8]:
arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [9]:
arr1*arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

### Splitting Array
divides the array into subarrays along a specified axis

In [10]:
a = np.arange(10)
print('first array')
print(a)
print('\n')
print('splitting the array in 2 equal size arrays')
b = np.split(a,2)
print(b)
print('\n')

first array
[0 1 2 3 4 5 6 7 8 9]


splitting the array in 2 equal size arrays
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]




In [11]:
a=np.arange(30)
#splitting the array indicated first at 4, second 5- 7 remaining in 3rd
print('splitting the array indicated first at 3, second 5 and remaining in 3rd')
c=np.split(a,[4,8])
print(c)
print('\n')

splitting the array indicated first at 3, second 5 and remaining in 3rd
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29])]




### Data Types for ndarray
*data type* or `dtype` cobtains the information about the type of data

In [12]:
array1 = np.array([3, 4, 5], dtype = np.float64)

In [13]:
array1

array([3., 4., 5.])

In [14]:
array2 = np.array([3.5, 4.6, 5.5], dtype = np.int32)

In [15]:
array2

array([3, 4, 5])

In [16]:
array2

array([3, 4, 5])

In [17]:
array1.dtype

dtype('float64')

In [18]:
array2.dtype

dtype('int32')

The numerical data types are names same way<br>
a *type name* `int` or `float` followed by number of bits per element<br>
Standard doubleprecision floating-point value takes 8 bytes or 64 bits. So it is known as `float64` in Numpy<br>

### Numpy Data Types

`int8`, `uint8` - Signed and unsigned 8-bit (1 byte) integer types<br>
`int16`, `uint16` - Signed and unsigned 16-bit integer types<br>
`int32`, `uint32` - Signed and unsigned 32-bit integer types<br>
`int64`, `uint64` - Signed and unsigned 64-bit integer types<br>
`float16` - Half-precision floating point<br>
`float32` - Standard single-precision floating point; compatible with C float<br>
`float64` - Standard double-precision floating point; compatible with C double and Python float object<br>
`float128` - Extended-precision floating point<br>
`complex64`,
`complex128`,
`complex256` - Complex numbers represented by two 32, 64, or 128 floats, respectively<br>
`bool` - Boolean type storing True and False values<br>
`object` - Python object type; a value can be any Python object<br>
`string_` - Fixed-length ASCII string type (1 byte per character)<br>
`unicode_` U Fixed-length Unicode type (number of bytes platform specific)<br>

### Casting
You can convert or cast an array from one data type to another

In [19]:
arra1 = np.array([1, 2, 3, 4, 5])

In [20]:
arra1.dtype

dtype('int32')

In [21]:
arra1.astype(np.float64)

array([1., 2., 3., 4., 5.])

If the float is casted into int, the decimal is truncated

In [22]:
arra1 = np.array([1.5, 2.9, 3.1, 4.0])
arra1.astype(np.int32)

array([1, 2, 3, 4])

You can convert a string representing numbers into number using `astype`

In [27]:
arra1 = np.array(['2.3', '5.6', '3.55789'], dtype=np.string_)

In [28]:
arra1.dtype

dtype('S7')

In [26]:
arra1

array([b'2.3', b'5.6', b'3.55'], dtype='|S4')

In [29]:
arra1.astype(np.float64)

array([2.3    , 5.6    , 3.55789])

### Arithmetic with Numpy Array
Numpy support the batch operations on data without `for` loops. This is call as *vectorization*

In [30]:
alist=[1,2,3,4,5]
list2=[6,7,8,9,2]
alist+list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2]

In [31]:
alist*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [34]:
alist*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [32]:
alist
for i in alist:
    j=i**2
    print(j)

1
4
9
16
25


In [35]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [37]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#array[1,2,3]* array2[[2,4,5,6][5,6,7,8]]

In [ ]:
1/arr

In [ ]:
arr**0.5

#### Comparision of array

In [ ]:
arr2 = np.array([[3,4,5],[6,2,8]])
arr2

In [ ]:
arr1

In [ ]:
arr2>arr1

### Array Indexing
You can access data in Numpy using Indexing

#### One Dimensional Indexing
You can access One Dimensional Indexing using bracket operator [] by specifying the zero offset value

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[1]

In [ ]:
arr[4]

If you specify too large value of index, you will get IndexError

In [ ]:
arr[10]

***
You can use negative index to get value offset from end 

In [ ]:
arr[-1]


In [ ]:
arr[-2]

### Two Dimensional Index
use comma to separate the index of each dimension

In [3]:
arr2d=np.array([[10, 20, 30],[40, 50, 60]])
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [2]:
import numpy as np

In [ ]:
print(arr2d[0,0])
print(arr2d[0,1])
print(arr2d[1,0])


If we are interested in all the items in a row, we can leave the second dimension index empty

In [1]:
import numpy as np
arr2d=np.array([[10, 20, 30],
       [40, 50, 60]])

In [2]:
arr2d[1,]

array([40, 50, 60])

## Array Slicing
slicing is specified using a colon operator `:` with *from* and *to* arguements<br>
`data[from:to]`

### One Dimensional Slicing
You can index all data using slice : with no index

In [ ]:
arr

In [ ]:
arr[:]

In [ ]:
arr[:2]

The elements in array can be sliced by inputting the slice `from` and `to` index. Slice starts from `from` index and stop one index before `to`. For example:[3,5] will have index 3 and 4 but not 5

In [ ]:
arr2d

In [ ]:
arr[0]

In [ ]:
arr[0:1]

#### Negative Index
Negative index takes the slice to the end of the dimension and count from end. `-2` index in `from` means, counting starts two from end and `to` means number of steps in forward direction. If we leave `to` blank, it would go till end

In [3]:
import numpy as np
arr =np.array([20,30,40,50])

In [4]:
arr[-2:]

array([40, 50])

In [5]:
arr[-3:-1]

array([30, 40])

#### Assign a value to a slice
A scalar value can be assigned to a slice also. It broadcasts to the whole slice. 

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([12,13,14,15,16,17])

In [ ]:
arr1

In [ ]:

arr2=arr1

In [ ]:
arr2

In [ ]:
arr2[3:5]

In [ ]:
arr2[3:5]=20

In [ ]:
arr2

In [ ]:
arr1

<div class="alert alert-block alert-info">
<b>Tip:</b> Array slices create a view on the array. The array is not copied. Any change in any element of array slice will change the element in original array
</div>

In [ ]:
slice_arr = arr1[3:5]

In [ ]:
slice_arr

In [ ]:
slice_arr[1] = 22

In [ ]:
slice_arr[1]

In [ ]:
arr1

In [ ]:
slice_arr[:] = 100
slice_arr

In [ ]:
arr1

#### Step Parameter
Python slice object can be created by using start, stop and step parameters<br>
arr1[1:7:2]<br>
means slicing starts from 1 upto 7 (7 not included) with step of 2

In [ ]:
arr1

In [ ]:
arr1[0:6:3]

### Two Dimensional Slicing
In two dimensional slicing, the elements at index are not scalars but they are one dimensional array

In [ ]:
arr2d

In [11]:
arr2d[2:3] #First row onwards

array([], shape=(0, 3), dtype=int32)

In [5]:
arr2d[1:2]

array([[40, 50, 60]])

In [ ]:
arr2d[2:3]

In [6]:
arr2d[0:1] #Upto first row

array([[10, 20, 30]])

In [7]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
arr2d[1,0] #For individual element

40

In [ ]:
arr2d[2,1]

In [12]:
arr2d[0,2]#first row last column

30

In [ ]:
arr2d

In [13]:
arr2d[:,0] #all rows column at  index 1

array([10, 40])

In [14]:
arr2d[:,1]

array([20, 50])

In [15]:
arr2d[:,0:1] #all rows column at index 0

array([[10],
       [40]])

In [16]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
arr2d[1:,1:3]

array([[50, 60]])

In [18]:
arr2d[1:,2:3]

array([[60]])

In [19]:
arr2d[1:,1:2]

array([[50]])

In [22]:
arr2d[:2,]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr2d[:2,1]

In [23]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
arr2d[:3,2:]

array([[30],
       [60]])

In [26]:
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
print(arr2d[2])

print(arr2d[2].shape)


IndexError: index 2 is out of bounds for axis 0 with size 2

### Multidimensional Array

In [3]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [2]:
import numpy as np

In [4]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d.ndim

3

In [6]:
arr3d[:,0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
arr3d[:,0:1,2:3]

array([[[3]],

       [[9]]])

In [38]:
arr3d[0:2,0:2,2:3]

array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])

In [8]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0,0, 1]

2

In [10]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [11]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d[0:,0:1,2:3]

array([[[3]],

       [[9]]])

### Boolean Index

In [13]:
names = np.array(['sam','bob','nick','sally','tom','sam','tina'])
data = np.random.randn(7,4)
names

array(['sam', 'bob', 'nick', 'sally', 'tom', 'sam', 'tina'], dtype='<U5')

In [14]:
data

array([[ 0.22998981,  0.82255012, -0.81136234, -0.56281801],
       [ 0.05164505,  0.42779   ,  0.89808284, -0.71087556],
       [-0.20567352,  0.79854022,  0.55316987,  0.53783341],
       [-0.73836797,  0.67681869, -0.74722815,  0.32315273],
       [-1.22363653, -0.99227221, -1.33644921,  1.8621857 ],
       [-0.08105781, -0.46843187, -0.48772804,  0.64447163],
       [ 1.70586674, -2.44774214,  0.18979663,  1.51186768]])

In [15]:
names == 'sam' # comparasion with array are also vectorized. This yields boolean array

array([ True, False, False, False, False,  True, False])

In [16]:
data[names=='sally'] # returns the rows where the boolean array has value True

array([[-0.73836797,  0.67681869, -0.74722815,  0.32315273]])

boolean array should have same length as axis it is indexing. You can mix and match boolean rray with slicing

In [17]:
data[names == 'sally', 0:2]

array([[-0.73836797,  0.67681869]])

In [ ]:
data[names == 'sam', ]

In [ ]:
data[names == 'sam', 1:2]

***
To select everthing except 'sam', you can use `!=` or `~`

In [18]:
names

array(['sam', 'bob', 'nick', 'sally', 'tom', 'sam', 'tina'], dtype='<U5')

In [19]:
names != 'sam'

array([False,  True,  True,  True,  True, False,  True])

In [20]:
data[~(names == 'sam')]

array([[ 0.05164505,  0.42779   ,  0.89808284, -0.71087556],
       [-0.20567352,  0.79854022,  0.55316987,  0.53783341],
       [-0.73836797,  0.67681869, -0.74722815,  0.32315273],
       [-1.22363653, -0.99227221, -1.33644921,  1.8621857 ],
       [ 1.70586674, -2.44774214,  0.18979663,  1.51186768]])

In [21]:
mask = (names == 'sam') | (names=='bob') # for more than 1 condition. Use and (&), or or(|)
mask

array([ True,  True, False, False, False,  True, False])

In [22]:
data[mask]

array([[ 0.22998981,  0.82255012, -0.81136234, -0.56281801],
       [ 0.05164505,  0.42779   ,  0.89808284, -0.71087556],
       [-0.08105781, -0.46843187, -0.48772804,  0.64447163]])

In [23]:
data[data<0]

array([-0.81136234, -0.56281801, -0.71087556, -0.20567352, -0.73836797,
       -0.74722815, -1.22363653, -0.99227221, -1.33644921, -0.08105781,
       -0.46843187, -0.48772804, -2.44774214])

In [24]:
data[data>1]

array([1.8621857 , 1.70586674, 1.51186768])

### Array Reshaping
In machine learning and deep learning, you need to reshape data as per requirement of the model
#### Data Shape
`shape` attribute returns the tuple of the length of each dimension of the array

In [25]:
arr1 = np.array([11, 22, 33, 44, 55])
arr1.shape

(5,)

In [27]:
arr2d = np.array([[11, 22, 33],[44, 55, 66]])
arr2d.shape

(2, 3)

In [28]:
print('Row %d' %arr2d.shape[0])
print('Column %d' %arr2d.shape[1])


Row 2
Column 3


### Reshape Array from 1D to 2D
`reshape` - to reshape the array<br>
takes single argument to specify new shape<br>
if you want to reshape 1d array to 2d array with 1 column, you can use `arr1.shape[0]` for first and 1 for second dimension

In [29]:
arr1 = np.array([11, 22, 33, 44, 55])
print(arr1)
print(arr1.shape)

[11 22 33 44 55]
(5,)


In [30]:
print(arr1.reshape((arr1.shape[0],1)))
print(arr1.reshape((arr1.shape[0],1)).shape)

[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [31]:
arr1 = np.array([11, 22, 33, 44, 55,66,77,88,99])
print(arr1)
print(arr1.reshape(3,3))#element here



[11 22 33 44 55 66 77 88 99]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2.reshape(2,3)

### From 2D to 3D

In [1]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [2]:
arr1.ndim

2

In [3]:
arr1.shape[0]

3

In [4]:
arr1.shape[1]

3

In [5]:
arr1 = arr1.reshape(arr1.shape[0], arr1.shape[1],1)
print(arr1)
print(arr1.shape)
arr1.ndim

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


3

In [6]:
arr1 = arr1.reshape(3, 3,1)
print(arr1)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


### Writing and loading array

In [1]:
import numpy as np
arr0=np.arange(20)
np.savetxt('arr0.csv',arr0)

In [2]:
np.loadtxt('arr0.csv')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
arr0=np.arange(10) #saving array into npy file
np.save('arrn.npy',arr0)

In [ ]:
np.load('arrn.npy')

### From Flattening arrays

In [ ]:
arr1

In [201]:
arr1=np.array([[12,33,40],[33,44,55]])

In [202]:
arr1

array([[12, 33, 40],
       [33, 44, 55]])

In [203]:
arr1.ndim

2

In [204]:
a=arr1.ravel()#ravel also change original array
a.ndim
a

array([12, 33, 40, 33, 44, 55])

In [205]:
a[2:4]=66
a

array([12, 33, 66, 66, 44, 55])

In [210]:
arr1

array([[12, 33, 66],
       [66, 44, 55]])

In [206]:
arr1
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [207]:

b=arr2.flatten() # it did not change origional array
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
b[2:5]=130
b

array([  1,   2, 130, 130, 130,   6,   7,   8,   9])

In [209]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Broadcasting
### Array Arithmetic Limitations
Array with different shape and size cannot be added or subtracted in Arithmetic<br>
A one dimensional array with length 8 can be added or subtracted from another array of length 8 only<br>
This limittion in arithmetic is limiting<br>
Python has builitin functionlity **broadcasting** to address this

### Broadcasting

Broadcasting solves the problems of different shapes by replicating the smaller array along the last mismatched dimension

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

* NumPy operations are usually done on pairs of arrays on an **element-by-element** basis
* Broadcasting provides a means of vectorizing array operations.
* In the simplest case, the two arrays must have exactly the same shape.

In [1]:
import numpy as np
a1 = np.array([1.0, 2.0, 3.0])
b1 = 2.0
a1 * b1

array([2., 4., 6.])

![alt text](https://numpy.org/doc/stable/_images/broadcasting_1.png)

* NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:



In [2]:
a2 = np.array([1.0, 2.0, 3.0])
b2 = np.array([2.0, 2.0, 2.0])
a2 * b2

array([2., 4., 6.])

In [3]:
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


### 2D array and Scalar

In [212]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = 4
print(b)
c = a + b # scalar b will duplicate itself 5 more times to broadcast
print(c)

[[1 2 3]
 [4 5 6]]
4
[[ 5  6  7]
 [ 8  9 10]]


* The result is equivalent to the previous example where b was an array. 
* We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as __a__. 
* The new elements in b, are simply copies of the original scalar. 
* The stretching analogy is only conceptual. 
* NumPy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible.

### 1D and 2D Array Broadcasting

In [213]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = np.array([7, 8, 9])
print(b)
c = a+b  # 1D array b is broadcast across each row of 2D by creating a copy of itself
print(c)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


### Limitation of Broadcasting

Broadcasting can be performed when<br>
1. the shape of each dimension in the array are equal<br>
or
2. one has dimension size 1

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a')
print(a)
print(a.shape)
b = np.array([6,7])
print('b')
print(b)
print(b.shape)
c = a+b #attempt to broadcast
print(c)

a
[[1 2 3]
 [4 5 6]]
(2, 3)
b
[6 7]
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
x = 'abcd'

for i in range(x):

    print(i)

In [ ]:
fish_list=['Bowfin','Cod','Herring','Ray']
fish_list.insert(5,'Sunfish')
fish_list